; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
upload_port = hwid://2341:0043  ; ls /dev/cu.*  | command run on Mac Terminal to find the current port
monitor_port = hwid://2341:0043
monitor_speed = 9600

; no framework = bare metal
test_framework = unity

; The board's IDs in Terminal:
; system_profiler SPUSBDataType 2>/dev/null | grep -E "Arduino|Product ID|Vendor ID"

; use hardware ID, The Uno has a fixed USB hardware ID that never changes regardless of port number:
; [env:uno]
; platform = atmelavr
; board = uno
; monitor_speed = 9600
; upload_port = hwid://2341:0043
; monitor_port = hwid://2341:0043

;2341 is Arduino's USB vendor ID, 0043 is the Uno's product ID
; This will always find your Uno specifically even if other serial devices are plugged in
; ** aside, command : lsof | grep usbmodem  shows exactly which app is holding usb port
